# Generated by Django 4.1 on 2022-08-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('budget', models.PositiveIntegerField()),
                ('employment', models.PositiveIntegerField()),
                ('joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
